services:
  - type: web
    name: smart-interz-liver-prediction
    env: python
    buildCommand: pip install --upgrade pip wheel setuptools && pip install -r requirements.txt
    startCommand: gunicorn Flask.app:app  # ✅ Refers to Flask/app.py file correctly
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
